name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: wget http://getcomposer.org/composer.phar
      - run: php composer.phar install
      - run: phpunit --bootstrap ./vendor/autoload.php ./tests/*

